import request, { gql } from 'graphql-request';
import { GetKeyDataResponse } from './types';
import fs from 'fs';

(async function () {
  const {
    getKeyData: { keys },
  } = await request<GetKeyDataResponse>(
    'https://oryx.zsa.io/graphql',
    gql`
      query {
        getKeyData(since: 0) {
          keys {
            code
            description
            label
          }
        }
      }
    `
  );

  const keyDataEnum = `export enum KeyCode {
${keys
      .map(
        (key) => `    /**
     * ${key.label}${key.description ? `- ${key.description}` : ''}
     */
    ${key.code} = '${key.code}',`
      )
      .join('\n')}
}`;

  const keyDataMap = `export const KeyData: Record<KeyCode, Omit<Key, 'keyCategoryId'>> = {
${keys.map(key => `    [KeyCode.${key.code}]: ${JSON.stringify(key)},`).join('\n')}
}`;

  const text = `// This file is generated by running \`yarn get-key-data\`!
import { Key } from './types';
${keyDataEnum};
${keyDataMap};
`;

  await fs.promises.writeFile('src/key-data.ts', text);
})();
