import request, { gql } from 'graphql-request';
import { GetKeyDataResponse } from './types';
import fs from 'fs';

(async function () {
  const {
    getKeyData: { keys },
  } = await request<GetKeyDataResponse>(
    'https://oryx.zsa.io/graphql',
    gql`
      query {
        getKeyData(since: 0) {
          keys {
            code
            description
            label
          }
        }
      }
    `
  );

  const enumStr = `
// This file is generated by running \`yarn get-key-data\`!
export enum KeyCode {
    ${keys
      .map(
        (key) => `    /**
     * ${key.label}${key.description ? `- ${key.description}` : ''}
     */
    ${key.code} = '${key.code}',`
      )
      .join('\n')}
}
  `;
  await fs.promises.writeFile('src/key-data.d.ts', enumStr);
})();
